# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='head_img',
            field=models.ImageField(default=0, upload_to=b'statics/imgs/upload'),
            preserve_default=False,
        ),
    ]
